version: "3.5"
services:
    php:
        working_dir: /var/www/dev-php
        build: ./docker
        volumes:
            - /var/www/icehrm/current:/var/www/dev-php:cached
        environment:
            APP_DEBUG: "true"
        ports:
            - 80:80
        links:
            - mysql
        depends_on:
            - mysql

    mysql:
        image: percona:5.5
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: icehrm
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
        #ports:
            #- 3307:3306
        volumes:
            - icehrm-mysql-volume:/var/lib/mysql
volumes:
  icehrm-mysql-volume:
